name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build -- --base=/molexplorer/pr-${{ github.event.pull_request.number }}/
      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true
      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const url = `https://${owner}.github.io/${repo}/pr-${pr}/`;
            const marker = '<!-- preview-url -->';
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: pr });
            const existing = comments.find(c => c.body && c.body.startsWith(marker) && c.user.login === 'github-actions[bot]');
            const body = `${marker}\nPreview: ${url}`;
            if (existing) {
              await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
            } else {
              await github.rest.issues.createComment({ owner, repo, issue_number: pr, body });
            }

  cleanup-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Remove preview directory
        run: |
          rm -rf pr-${{ github.event.pull_request.number }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Remove preview for PR #${{ github.event.pull_request.number }}" || echo "No preview to remove"
          git push origin gh-pages
      - name: Delete preview comment
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const marker = '<!-- preview-url -->';
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: pr });
            const existing = comments.find(c => c.body && c.body.startsWith(marker) && c.user.login === 'github-actions[bot]');
            if (existing) {
              await github.rest.issues.deleteComment({ owner, repo, comment_id: existing.id });
            }
